# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico


# Content configuration version
version: 2

# Personal info
name: Rachel Jones
title: Student
email: rachel.jonesdestiny@gmail.com
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Text color (red/orange/yellow)
textcolor: red

# Social links
twitter_username: n/a
github_username:  rj34260
# stackoverflow_username: "00000001"
# dribbble_username: n/a
# facebook_username: n/a
# flickr_username: n/a
instagram_username: n/a
linkedin_username: n/a
# xing_username: n/a
# pinterest_username: n/a
youtube_username: n/a
# googleplus_username: n/a
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: n/a
  icon: fas fa-basketball-ball
  url: https://hfcwarriorsokc.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: https://photos.fife.usercontent.google.com/pw/AP1GczPIkDfEXO9C0wfWebpFP5pHfg1T6brFJXzxKCavgYNphMAXffuCO2Dl=w736-h736-s-no-gm?authuser=1
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rachel and I'm a senior in high school. I'm interested in helping animals in shelters and building/creating things. I have some experience in basic tech and am currently trying to broaden my skill set.
  

  I am most skilled in: training dogs and counseling kids

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Projects I've done!
        link: 
        # link_text: 
        additional_links:
          - title: Shiloh Adventures
            icon: far fa-star
            url: https://shilohadventures.org/
          # - title:  project page (https://shilohadventures.org/)
          #   icon: far fa-star
          #   url: Link to project (https://shilohadventures.org/)
        quote: > 
        description: | # this will include new lines to allow paragraphs
                I've done a couple of projects over the past 5 years. When I was around 13-14 I helped a family build their entertainment system including their entertainment stand. After I built the stand I hooked up their two TVs and connected their devices to their wifi. Everyone thought setting up that system was difficult but it seemed like second nature to me. I've done a couple of projects at a non-profit camp called Shiloh Adventures. We installed turf into this sloppy hill, cleared tree debris from their streets, built a volleyball pit, and did a little landscaping from time to time. I've also applied to help volunteer at an animal shelter. (edit)title: Shiloh Adventures link: https://shilohadventures.org/ # link_text: shiloh.com sub_title: Summer Camp Counselor caption: May 2023 - Present



  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left, center
       
        title: YMCA
        link: https://ymcaokc.org/
        # link_text: ymca.com
        sub_title: Lifeguard
        caption: October 2024 - Present
        quote: >
           Looking for opportunities to help the people and animals in my community
        description: | # this will include new lines to allow paragraphs
           I enjoy helping all around. No matter if that's kids, teens, adults, or animals.  If we all help each other our communities will get stronger and strive.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Will Rogers Elementary - Epic Charter Schools
        caption: 2011 - present
        sub_title: Junior/Senior
        quote: >
        description: | # this will include new lines to allow paragraphs
        
          I started in Will Rogers Elementary since Pre-K but then transferred to homeschooling with Epic Charter Schools before 5th grade started.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in animal welfare and sports, some of my other interests and hobbies are:
      - Watching tv
      - Mind Puzzles
      - Fitness
      - Baking
   

   Look at this cool image!  
![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
